### ISSUE TITLE
Migrate to decentralized graph

### ISSUE THREAD

**Issue by scottrepreneur** [talentlessguy/get-ens#2]
The hosted version of TheGraph will be deprecated soon. Adjusting the API url and handling the API key should allow users of this library to continue using this with the decentralized version of TheGraph.

**Comment by talentlessguy** [comment]
Could you please submit a PR with the new API?

**Comment by talentlessguy** [comment]
I just tried to obtain an API key from TheGraph and the website is broken and doesn't let me get one :/

**Comment by v1rtl** [comment]
from version 2.1 you can pass a custom `endpointUrl`, I hope this fixes it
